### ISSUE TITLE
Plugin not working with eslint 8.3.0

### ISSUE THREAD

**Issue by Bartheleway** [forcedotcom/eslint-plugin-aura#34]
Hi,

I can't get the plugin to work with eslint 8.3.0. I get an issue in ESLint saying that it can't find the plugin @salesforce/eslint-plugin-aura

Could you fix ? Or maybe this plugin is deprecated ?

Best regards

**Comment by PawelWozniak** [comment]
I have simillar issue. Trying to update eslint to v8 give error
Could not resolve dependency:
npm ERR! peer eslint@"^7" from @salesforce/eslint-plugin-aura@2.0.0
npm ERR! node_modules/@salesforce/eslint-plugin-aura
npm ERR!   dev @salesforce/eslint-plugin-aura@"^2.0.0" from the root project

**Comment by PawelWozniak** [comment]
@pmdartus Thank you for updating dependencies. 
When this version of the package will be available in npm? 
I am getting additional errors from dependency eslint-plugin-compat v3.
Since you have changed it to v4 which supports eslint 8 it would solve that issue too:

Could not resolve dependency:
npm WARN peer eslint@"^4.0.0 || ^5.0.0 || ^6.0.0 || ^7.0.0" from eslint-plugin-compat@3.13.0
npm WARN node_modules/eslint-plugin-compat
npm WARN   eslint-plugin-compat@"^3.9.0" from @salesforce/eslint-plugin-aura@2.0.0
npm WARN   node_modules/@salesforce/eslint-plugin-aura

Looking forward to the package update in npm registry.

**Comment by pmdartus** [comment]
Released as part of [2.1.0](https://github.com/forcedotcom/eslint-plugin-aura/releases/tag/v2.1.0).

**Comment by PawelWozniak** [comment]
Thank you. It solved all issues.

**Comment by Bartheleway** [comment]
Thanks for the update. It seems to run fine but with some issues :
- I can't define manually the level of error of each rules, I get `Definition for rule 'aura/...' was not found`
- Using `plugin:@salesforce/eslint-plugin-aura/locker`, I get `Expected an assignment or function call and instead saw an expression.` for a line like `doInit: function doInit (component, event, helper) {`
